trigger:
  batch: true
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

schedules:
  - cron: '0 0 * * 0'
    displayName: Weekly build
    branches:
      include:
        - main
    always: true

resources:
  repositories:
    - repository: OpsGuildAutomationRepo
      type: git
      name: Engineering/OpsGuild.Automation
      ref: refs/heads/main
    - repository: templates
      type: github
      name: osisoft/OSI-Samples
      endpoint: osisoft/OSI-Samples

variables:
  - template: '/miscellaneous/build_templates/variables.yml@templates'
  - name: analysisProject
    value: Auth-CC_Rust

parameters:
  - name: pool
    default: 00-OSIManaged-Containers
  - name: containerDemands
    type: object
    default: ['Agent.OS -equals Linux']

jobs:
  - job: Tests
    condition: ne(variables['Build.Reason'], 'Schedule')
    pool:
      name: ${{ parameters.pool }}
      demands: ${{ parameters.containerDemands }}
    steps:
      - template: '/miscellaneous/build_templates/appsettings.yml@templates'
        parameters:
          secrets: 'TenantId, ClientId, ClientSecret, Resource'

      - script: curl https://sh.rustup.rs -sSf | sh -s -- -y
        displayName: 'Install Rust'

      - script: |
          sudo apt update
          sudo apt-get install gcc
        displayName: 'Install linker'

      - script: |
          source $HOME/.cargo/env
          cargo test --all
        displayName: 'Run tests'
        condition: always()

      - script: |
          source $HOME/.cargo/env
          cargo clippy --all
        displayName: 'Run clippy'
        condition: always()

  - template: '/miscellaneous/build_templates/code-analysis.yml@templates'
    parameters:
      skipPolaris: true
