[package]
name = "adh-client-creds-rust"
version = "1.0.4"
edition = "2021"
authors = ["AVEVA <samples@osisoft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.11", features = ["json"] }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
tokio = { version = "1.19.2", features = ["full"] }
