[package]
name = "ocs-client-creds-rust"
version = "1.0.0"
edition = "2021"
authors = ["OSIsoft, LLC <samples@osisoft.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"